window.TEK17Advisor = window.TEK17Advisor || {};

const chapter11Defaults = {
  practicalMeaning: "Bruk treffet sammen med byggverkets dokumenterte forutsetninger og kontroller hele bestemmelsen hos DIBK.",
  assessmentNote: "Kontroller at alle vilkår og tilgrensende bestemmelser er vurdert før dette brukes i prosjektering.",
  outsidePreaccepted: "Hvis løsningen eller forutsetningene ikke dekkes av ytelsen, må oppfyllelse av funksjonskravet dokumenteres særskilt.",
};

function sourceChunk(source) {
  return {
    practicalMeaning: chapter11Defaults.practicalMeaning,
    assessmentNote: chapter11Defaults.assessmentNote,
    outsidePreaccepted: chapter11Defaults.outsidePreaccepted,
    keyPoints: [],
    phrases: [],
    topics: [],
    ...source,
  };
}

window.TEK17Advisor.sources = [
  sourceChunk({
    id: "11-1-requirement",
    section: "TEK17 § 11-1",
    paragraph: "første til fjerde ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-1 Sikkerhet ved brann: overordnede krav",
    referenceKeys: ["section11_1"],
    topics: ["tek17", "byggteknisk forskrift", "vtek", "sikkerhet ved brann", "brannsikkerhet", "funksjonskrav", "liv og helse", "materielle verdier", "miljø", "samfunnsinteresser"],
    phrases: ["tilfredsstillende sikkerhet ved brann", "overordnede krav", "vesentlige samfunnsinteresser"],
    shortAnswer: "TEK17 er byggteknisk forskrift. § 11-1 krever tilfredsstillende sikkerhet ved brann for personer, materielle verdier, miljø og samfunnsmessige forhold.",
    practicalMeaning: "§ 11-1 er det overordnede funksjonskravet. De mer konkrete preaksepterte ytelsene finnes under de øvrige paragrafene i kapittel 11.",
    assessmentNote: "Et konkret svar må normalt forankres i en mer spesifikk paragraf enn § 11-1 alene.",
    vtekSearch: "Finn først hvilket brannfaglig tema i §§ 11-2 til 11-17 problemstillingen gjelder.",
    preacceptedPath: "Bestemmelsen har ikke ett samlet preakseptert løsningssett; ytelsene følger av de øvrige paragrafene.",
  }),
  sourceChunk({
    id: "11-2-criteria",
    section: "TEK17 § 11-2",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-2 Risikoklasse: kriterier",
    referenceKeys: ["risk"],
    topics: ["risikoklasse", "rkl", "personopphold", "selvredning", "rømning", "overnatting", "brannfare"],
    phrases: ["kjenner rømningsforholdene", "bringe seg selv i sikkerhet", "forutsatt bruk"],
    shortAnswer: "Risikoklasse fastsettes ut fra forutsatt bruk og hvilken trussel en brann kan innebære for liv og helse.",
    practicalMeaning: "Vurder personopphold, kjennskap til rømningsforhold, evne til selvredning, overnatting og om brannfaren er liten.",
    vtekSearch: "Kontroller kriteriene i § 11-2 før en virksomhetstype sammenlignes med tabellen i veiledningen.",
    preacceptedPath: "Kriteriene er forskriftsgrunnlaget; tabellplasseringen er et veiledet, preakseptert spor.",
  }),
  sourceChunk({
    id: "11-2-table",
    section: "Veiledning til TEK17 § 11-2",
    paragraph: "tabell 1",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-2 Risikoklasse: virksomhetstabell",
    referenceKeys: ["riskGuide"],
    topics: ["risikoklasse", "rkl", "virksomhetstype", "hotell", "skole", "barnehage", "bolig", "kontor", "lager", "sykehjem", "garasje"],
    phrases: ["virksomhetstabell", "tabell for risikoklasse", "hvilken risikoklasse"],
    shortAnswer: "Veiledningens tabell angir risikoklasse for vanlige virksomhetstyper når de oppgitte forutsetningene passer.",
    practicalMeaning: "Et tabelltreff må kontrolleres mot den faktiske bruken. Tabellen kan ikke brukes mekanisk når kriteriene eller virksomheten avviker.",
    assessmentNote: "Blandet eller uvanlig bruk kan kreve separat klassifisering av ulike bruksområder.",
    vtekSearch: "Finn virksomhetstypen i tabell 1 og sammenlign den med kriteriene i forskriften.",
    preacceptedPath: "Et passende tabelltreff med samsvarende forutsetninger kan normalt legges til grunn.",
    keyPoints: [
      "RKL 1-6 uttrykker ulike kombinasjoner av bruk, rømningsforutsetninger, overnatting og brannfare.",
      "Virksomheter uten treff eller med avvikende forutsetninger krever en begrunnet vurdering.",
    ],
  }),
  sourceChunk({
    id: "11-3-normal-table",
    section: "Veiledning til TEK17 § 11-3",
    paragraph: "tabell 1",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-3 Brannklasse: normal tabell",
    referenceKeys: ["fire", "fireGuide"],
    topics: ["brannklasse", "bkl", "risikoklasse", "etasjer", "konsekvens", "normal tabell"],
    phrases: ["brannklasse for", "antall etasjer", "byggets totale antall etasjer"],
    shortAnswer: "Normalsporet kobler risikoklasse og byggverkets totale antall etasjer til brannklasse.",
    practicalMeaning: "Fastsett risikoklasse og totalt etasjeantall før tabellen brukes, og kontroller deretter unntak og mulige BKL 4-forhold.",
    vtekSearch: "Slå opp kombinasjonen av risikoklasse og etasjeantall i tabell 1.",
    preacceptedPath: "Tabellresultatet kan brukes når byggverket passer tabellens forutsetninger og ingen unntak eller særforhold slår inn.",
    keyPoints: [
      "RKL 2-4 gir normalt BKL 1 i én til to etasjer, BKL 2 i tre til fire etasjer og BKL 3 fra fem etasjer.",
      "RKL 5 gir normalt BKL 1 i én etasje, BKL 2 i to etasjer og BKL 3 fra tre etasjer.",
      "RKL 6 gir BKL 1 i én etasje, BKL 2 i to til fire etasjer og BKL 3 fra fem etasjer i normalsporet.",
    ],
  }),
  sourceChunk({
    id: "11-3-exceptions",
    section: "Veiledning til TEK17 § 11-3",
    paragraph: "preaksepterte unntak",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-3 Unntak fra normal brannklasse",
    referenceKeys: ["exceptions", "fireGuide"],
    topics: ["unntak", "lavere brannklasse", "forsamlingslokale", "salgslokale", "overnattingsbygg", "hotell", "bolig", "direkte terreng"],
    phrases: ["under 300 m2", "under 800 m2", "direkte utgang til terreng", "unntak for brannklasse"],
    shortAnswer: "Veiledningen har enkelte avgrensede unntak som kan gi lavere brannklasse når alle vilkårene er oppfylt.",
    practicalMeaning: "Kontroller bruk, areal, etasjer og utgangsforhold ord for ord mot det aktuelle unntaket.",
    assessmentNote: "At et bygg ligner et unntak er ikke nok; alle vilkårene må være oppfylt.",
    vtekSearch: "Sammenlign situasjonen med det konkrete unntaket i veiledningen til § 11-3.",
    preacceptedPath: "Et fullstendig treff på alle vilkår kan normalt behandles som preakseptert.",
    keyPoints: [
      "Forsamlings- og salgslokaler med høyst to etasjer og under 800 m² per etasje kan på angitte vilkår være BKL 1.",
      "Overnattingsbygg med høyst to etasjer og under 300 m2 i hver etasje kan på angitte vilkår være BKL 1.",
      "Boligbygning i RKL 6 med to etasjer kan på angitte vilkår være BKL 1.",
    ],
  }),
  sourceChunk({
    id: "11-3-mixed-use",
    section: "Veiledning til TEK17 § 11-3",
    paragraph: "blandet bruk",
    sourceType: "veiledning",
    title: "§ 11-3 Brannklasse ved blandet bruk",
    referenceKeys: ["mixedUse", "fireGuide"],
    topics: ["blandet bruk", "flere bruksområder", "underliggende etasje", "overliggende etasje", "kombinasjonsbygg"],
    phrases: ["ulike bruksområder", "underliggende etasje", "total etasjehøyde"],
    shortAnswer: "Ulike bruksområder klassifiseres etter aktuell bruk og byggverkets totale etasjeantall før samlet brannklasse vurderes.",
    practicalMeaning: "Del bygget i relevante bruksområder og kontroller at en underliggende etasje minst har samme brannklasse som etasjen over.",
    assessmentNote: "Komplekst samspill mellom bruksområder kan kreve særskilt dokumentasjon.",
    vtekSearch: "Identifiser hver bruk og sammenlign med veiledningen om underliggende og overliggende deler.",
    preacceptedPath: "Normalsporet kan brukes når delene kan klassifiseres tydelig og veiledningens forutsetninger følges.",
  }),
  sourceChunk({
    id: "11-3-bkl4",
    section: "TEK17 § 11-3",
    paragraph: "brannklasse 4",
    sourceType: "veiledning",
    title: "§ 11-3 Unntak og BKL 4: analysebehov",
    referenceKeys: ["exceptions", "fireGuide"],
    topics: ["bkl 4", "brannklasse 4", "analyse", "samfunnsinteresser", "under terreng", "farlige stoffer", "mer enn 16 etasjer"],
    phrases: ["særlig store konsekvenser", "fullstendig brannforløp", "vesentlige samfunnsinteresser"],
    shortAnswer: "Byggverk med særlig store konsekvenser ved brann plasseres i BKL 4, og sikkerheten må dokumenteres ved analyse.",
    practicalMeaning: "Vurder blant annet svært høye bygg, bygg hovedsakelig under terreng, viktige samfunnsfunksjoner og særlig farlig virksomhet.",
    assessmentNote: "BKL 4 kan ikke dokumenteres ved å bruke normal tabell alene.",
    vtekSearch: "Kontroller om ett eller flere av forholdene som peker mot BKL 4 er til stede.",
    preacceptedPath: "Det finnes ikke et komplett preakseptert tabellspor for BKL 4; analyse er nødvendig.",
  }),
  sourceChunk({
    id: "11-4-requirement",
    section: "TEK17 § 11-4",
    paragraph: "første til femte ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-4 Bæreevne og stabilitet",
    referenceKeys: ["section11_4"],
    topics: ["bæreevne", "stabilitet", "bæresystem", "konstruksjon", "brannmotstand", "kollaps"],
    phrases: ["bærende hovedsystem", "fullstendig brannforløp", "bæreevne under brann"],
    shortAnswer: "Byggverket og dets deler skal ha tilfredsstillende bæreevne og stabilitet under den forventede brannpåkjenningen.",
    practicalMeaning: "Kravet skal gi nødvendig tid til rømning, redning og slokking, og er strengere for BKL 3 og 4.",
    vtekSearch: "Fastsett brannklasse og identifiser hovedsystem, sekundære deler, etasjeskillere, trapper og konstruksjoner under terreng.",
    preacceptedPath: "For BKL 1-3 gir veiledningens tabell og unntak preaksepterte ytelser; BKL 4 krever beregning.",
  }),
  sourceChunk({
    id: "11-4-resistance",
    section: "Veiledning til TEK17 § 11-4",
    paragraph: "tabell 1 og unntak",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-4 Brannmotstand for bærende bygningsdeler",
    referenceKeys: ["section11_4"],
    topics: ["r 30", "r 60", "r 90", "brannmotstand", "hovedbæresystem", "takkonstruksjon", "trappeløp"],
    phrases: ["bærende bygningsdelers brannmotstand", "tabell 1 bæreevne"],
    shortAnswer: "Veiledningens tabell angir preakseptert brannmotstand for bærende deler ut fra brannklasse og bygningsdel.",
    practicalMeaning: "Tabellen må brukes sammen med unntakene for blant annet enkelte én-etasjes bygg, takkonstruksjoner og åpne parkeringshus.",
    vtekSearch: "Finn riktig rad for bygningsdelen og kolonne for brannklassen, og les alle tilhørende unntak.",
    preacceptedPath: "Tabellverdien med relevante vilkår og unntak er et preakseptert spor for BKL 1-3.",
  }),
  sourceChunk({
    id: "11-5-requirement",
    section: "TEK17 § 11-5",
    paragraph: "bestemmelsen",
    sourceType: "forskriftskrav",
    title: "§ 11-5 Sikkerhet ved eksplosjon",
    referenceKeys: ["section11_5"],
    topics: ["eksplosjon", "eksplosjonsfare", "trykkavlastning", "avlastningsflate", "farlig stoff", "fyrhus"],
    phrases: ["fare for eksplosjon", "trykkavlastningsflate", "avlastet trykk"],
    shortAnswer: "Byggverk med eksplosjonsfare skal ha avlastningsflater slik at personsikkerhet og bæreevne ivaretas.",
    practicalMeaning: "Eksplosjonsfarlige rom må identifiseres tidlig, og andre relevante sikkerhetsregelverk må også kontrolleres.",
    vtekSearch: "Avklar stoff, prosess, rom og mulig trykkretning før ytelsene vurderes.",
    preacceptedPath: "Veiledningen gir konkrete ytelser for branncelle, trykkavlastning og sikring av konstruksjoner.",
  }),
  sourceChunk({
    id: "11-5-preaccepted",
    section: "Veiledning til TEK17 § 11-5",
    paragraph: "preaksepterte ytelser",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-5 Eksplosjonsfarlige rom",
    referenceKeys: ["section11_5"],
    topics: ["eksplosjonsfarlig rom", "egen branncelle", "trykkavlastningsflate", "sikker retning"],
    phrases: ["rom med eksplosjonsfare", "egen branncelle", "minst én trykkavlastningsflate"],
    shortAnswer: "Rom med eksplosjonsfare skal etter veiledningen være egen branncelle og ha minst én trykkavlastningsflate mot sikker retning.",
    vtekSearch: "Kontroller plassering av avlastningsflaten og om konstruksjonene må forsterkes.",
    preacceptedPath: "Alle oppgitte ytelser om branncelle, avlastning, retning og bæreevne må følges samlet.",
  }),
  sourceChunk({
    id: "11-6-distance",
    section: "TEK17 § 11-6",
    paragraph: "annet til fjerde ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-6 Brannspredning mellom byggverk",
    referenceKeys: ["section11_6"],
    topics: ["brannspredning", "nabobygg", "avstand mellom bygg", "lave byggverk", "høye byggverk", "8 meter", "brannvegg"],
    phrases: ["mindre enn 8 meter", "minimum 8 meter", "spredning mellom byggverk"],
    shortAnswer: "Brannspredning mellom byggverk skal forebygges; avstand eller brannskillende konstruksjoner er sentrale tiltak.",
    practicalMeaning: "Lave byggverk har som utgangspunkt 8 meter innbyrdes avstand, med mulighet for kompenserende brannskille. Høye bygg krever brannvegg ved mindre avstand.",
    vtekSearch: "Avklar høyde, bruksenhet, innbyrdes avstand, bruttoareal og behov for brannvegg.",
    preacceptedPath: "Veiledningen beskriver branncellebegrensende skille for lave bygg og brannvegg for høye bygg ved avstand under 8 meter.",
  }),
  sourceChunk({
    id: "11-6-fire-wall",
    section: "Veiledning til TEK17 § 11-6",
    paragraph: "femte ledd",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-6 Brannvegg",
    referenceKeys: ["section11_6"],
    topics: ["brannvegg", "rei 120-m", "mekanisk motstand", "brannenergi", "over tak", "kollaps"],
    phrases: ["brannveggens brannmotstand", "føres over tak", "stå selv om byggverket raser"],
    shortAnswer: "Brannveggen skal hindre spredning mellom byggverk uavhengig av brannvesenets slokkeinnsats.",
    practicalMeaning: "Brannenergi, materialklasse, mekanisk motstand, stabilitet og avslutning mot tak og fasade må vurderes samlet.",
    vtekSearch: "Bruk tabellen for brannveggens motstand og kontroller detaljkravene til stabilitet og avslutninger.",
    preacceptedPath: "Tabellverdier og alle detaljytelser må oppfylles for å følge preakseptert spor.",
  }),
  sourceChunk({
    id: "11-7-section-size",
    section: "TEK17 § 11-7",
    paragraph: "første ledd og tabell 1",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-7 Brannseksjoner og seksjonsstørrelse",
    referenceKeys: ["section11_7"],
    topics: ["brannseksjon", "seksjonering", "seksjonsstørrelse", "bruttoareal", "brannenergi", "sprinkler", "røykventilasjon", "brannalarm"],
    phrases: ["største bruttoareal", "uten seksjonering", "deles i brannseksjoner"],
    shortAnswer: "Byggverk skal seksjoneres for å sikre rømning og redning, begrense tap og holde brannen i startseksjonen.",
    practicalMeaning: "Tillatt seksjonsareal avhenger av brannenergi og tiltak som brannalarm, sprinkler eller røykventilasjon.",
    vtekSearch: "Fastsett brannenergi og bruttoareal, og les riktig kolonne i tabell 1.",
    preacceptedPath: "Tabellens arealgrenser og vilkår for valgte aktive tiltak må oppfylles.",
  }),
  sourceChunk({
    id: "11-7-section-wall",
    section: "Veiledning til TEK17 § 11-7",
    paragraph: "annet ledd",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-7 Seksjoneringsvegg",
    referenceKeys: ["section11_7"],
    topics: ["seksjoneringsvegg", "rei-m", "innvendig hjørne", "vertikal seksjonering", "seksjoneringsdekke"],
    phrases: ["seksjoneringsveggens brannmotstand", "innvendig hjørne", "begrenses til brannseksjonen"],
    shortAnswer: "Seksjoneringsveggen skal begrense brannen til startseksjonen med påregnelig slokkeinnsats.",
    practicalMeaning: "Motstand, materialer, stabilitet og overgang mot tak, fasade og innvendige hjørner må løses sammenhengende.",
    vtekSearch: "Kontroller tabell 2 og detaljytelsene til veggens oppbygning og avslutninger.",
    preacceptedPath: "Tabellkrav og detaljytelser gir et preakseptert spor; horisontal seksjonering kan kreve analyse.",
  }),
  sourceChunk({
    id: "11-8-requirement",
    section: "TEK17 § 11-8",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-8 Oppdeling i brannceller",
    referenceKeys: ["section11_8"],
    topics: ["branncelle", "branncelleinndeling", "ulik risiko", "brannenergi", "rom", "boenhet"],
    phrases: ["egen branncelle", "deles opp i brannceller", "branncellebegrensende"],
    shortAnswer: "Byggverket skal deles hensiktsmessig i brannceller, særlig der bruk, risiko eller brannenergi er forskjellig.",
    practicalMeaning: "Brannceller skal gi tid til rømning, begrense brann og røyk og støtte slokkeinnsatsen.",
    vtekSearch: "Kartlegg romfunksjoner, risiko, brannenergi og rømningsbehov før branncelleinndelingen fastsettes.",
    preacceptedPath: "Veiledningen lister rom og funksjoner som normalt skal være egne brannceller.",
  }),
  sourceChunk({
    id: "11-8-typical-cells",
    section: "Veiledning til TEK17 § 11-8",
    paragraph: "første ledd, preaksepterte ytelser",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-8 Rom som skal være egne brannceller",
    referenceKeys: ["section11_8"],
    topics: ["trapperom", "rømningsvei", "sykerom", "gjesterom", "forsamlingslokale", "salgslokale", "boenhet", "teknisk rom"],
    phrases: ["hvert gjesterom", "hver boenhet", "egne brannceller"],
    shortAnswer: "Veiledningen angir en rekke rom og funksjoner som normalt må skilles ut som egne brannceller.",
    practicalMeaning: "Listen omfatter blant annet rømningsvei, trapperom, gjesterom i overnattingsbygg, forsamlingslokaler, salgslokaler og boenheter.",
    vtekSearch: "Finn den aktuelle romtypen i listen og kontroller etterfølgende ytelser for brannmotstand, dører, vinduer og sjakter.",
    preacceptedPath: "Den aktuelle romtypen og alle tilhørende skillekrav må følges.",
  }),
  sourceChunk({
    id: "11-9-materials",
    section: "TEK17 § 11-9",
    paragraph: "første og annet ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-9 Materialer og produkters egenskaper ved brann",
    referenceKeys: ["section11_9"],
    topics: ["materialer", "produkter", "overflate", "kledning", "isolasjon", "brennbar isolasjon", "røykutvikling", "fasade"],
    phrases: ["egenskaper ved brann", "brennbar isolasjon", "utvendig overflate"],
    shortAnswer: "Materialer og produkter skal ikke gi uakseptable bidrag til brannutvikling, røyk eller brannspredning.",
    practicalMeaning: "Kravene avhenger blant annet av brannklasse, risikoklasse, plassering og om materialet er overflate, kledning eller isolasjon.",
    vtekSearch: "Identifiser materialets funksjon og plassering før riktig klassifisert ytelse velges.",
    preacceptedPath: "Veiledningen gir tabeller og særregler for overflater, kledninger, fasader, tak og isolasjon.",
  }),
  sourceChunk({
    id: "11-9-insulation",
    section: "Veiledning til TEK17 § 11-9",
    paragraph: "isolasjon i bygningsdeler",
    sourceType: "veiledning",
    title: "§ 11-9 Brennbar isolasjon",
    referenceKeys: ["section11_9"],
    topics: ["brennbar isolasjon", "ubrennbar isolasjon", "tildekking", "fasade", "kompakt tak", "brannspredning"],
    phrases: ["isolasjon i bygningsdeler", "tildekkes mures eller støpes inn", "brytes ved branncelle"],
    shortAnswer: "Brennbar isolasjon kan brukes bare når bygningsdelens funksjon oppfylles og isolasjonen ikke bidrar til brannspredning.",
    practicalMeaning: "Tildekking, oppdeling ved brannskiller og beskyttelse mot tidlig involvering i brannen er sentrale vurderinger.",
    assessmentNote: "Løsningen må dokumentere hele bygningsdelen, ikke bare isolasjonsproduktet isolert.",
    vtekSearch: "Kontroller veiledningens særskilte ytelser for den aktuelle konstruksjonen og plasseringen.",
    preacceptedPath: "Bruk bare en uttrykkelig beskrevet løsning med alle beskyttelses- og oppdelingsvilkår oppfylt.",
  }),
  sourceChunk({
    id: "11-10-installations",
    section: "TEK17 § 11-10",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-10 Tekniske installasjoner",
    referenceKeys: ["section11_10"],
    topics: ["tekniske installasjoner", "ventilasjon", "kanal", "kabel", "rør", "gjennomføring", "branntetting", "oppheng"],
    phrases: ["gjennom brannskillende bygningsdel", "brann- og røykspredning", "tekniske gjennomføringer"],
    shortAnswer: "Tekniske installasjoner skal ikke øke faren vesentlig for antennelse eller spredning av brann og røyk.",
    practicalMeaning: "Ventilasjon, kanaler, kabler, rør, gjennomføringer og oppheng må bevare brannskillenes forutsatte funksjon.",
    vtekSearch: "Kartlegg alle kryssinger av brannskiller og installasjonenes nødvendige funksjonstid.",
    preacceptedPath: "Veiledningen gir konkrete ytelser for blant annet ventilasjon, gjennomføringer og isolasjon.",
  }),
  sourceChunk({
    id: "11-10-ventilation",
    section: "Veiledning til TEK17 § 11-10",
    paragraph: "ventilasjonsanlegg",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-10 Ventilasjon og gjennomføringer",
    referenceKeys: ["section11_10"],
    topics: ["ventilasjonsanlegg", "ventilasjonskanal", "kanalgods", "komfyravtrekk", "fettfilter", "branntetting"],
    phrases: ["ventilasjonskanal gjennom", "opprettholde brannmotstand", "avtrekk fra komfyr"],
    shortAnswer: "Kanaler og gjennomføringer skal utføres slik at brannskillets motstand og installasjonens nødvendige funksjonstid opprettholdes.",
    practicalMeaning: "Oppheng, materialbruk, tetting og rengjørbarhet må prosjekteres som deler av den samlede løsningen.",
    vtekSearch: "Kontroller både den generelle installasjonsveiledningen og ytelsene for aktuell kanal, rør eller kabel.",
    preacceptedPath: "Den valgte systemløsningen må være dokumentert og følge alle tilhørende monteringsforutsetninger.",
  }),
  sourceChunk({
    id: "11-11-escape",
    section: "TEK17 § 11-11",
    paragraph: "første og annet ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-11 Generelle krav om rømning og redning",
    referenceKeys: ["section11_11"],
    topics: ["rømning", "redning", "funksjonsnedsettelse", "rømningstid", "sikkerhetsmargin", "tilgjengelig rømningstid", "nødvendig rømningstid"],
    phrases: ["rask og sikker rømning", "tilgjengelig rømningstid", "nødvendig rømningstid", "tilfredsstillende sikkerhetsmargin"],
    shortAnswer: "Byggverket skal gi rask og sikker rømning og redning, også med hensyn til personer med funksjonsnedsettelse.",
    practicalMeaning: "Tilgjengelig rømningstid skal være større enn nødvendig rømningstid med tilfredsstillende sikkerhetsmargin.",
    assessmentNote: "Ved analyse må usikkerhet i både brannforløp og personforflytning dokumenteres.",
    vtekSearch: "Fastsett brukere, risikoklasse, rømningens faser og behov for bistand før detaljkrav vurderes.",
    preacceptedPath: "Detaljert preakseptert utforming følger særlig av §§ 11-12 til 11-14.",
  }),
  sourceChunk({
    id: "11-12-active-measures",
    section: "TEK17 § 11-12",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-12 Aktive tiltak for rømning og redning",
    referenceKeys: ["section11_12"],
    topics: ["aktive tiltak", "sprinkler", "brannalarm", "ledesystem", "røykventilasjon", "automatisk slokkeanlegg", "rømningstid"],
    phrases: ["påvirke rømnings- og redningstider", "øke tilgjengelig rømningstid", "automatisk brannslokkeanlegg"],
    shortAnswer: "Byggverk der rømning og redning kan ta lang tid skal ha aktive tiltak som øker tilgjengelig rømningstid.",
    practicalMeaning: "Aktuelle tiltak omfatter blant annet automatisk slokking, brannalarmanlegg, ledesystem og røykstyring, avhengig av bruk og størrelse.",
    vtekSearch: "Kontroller hvert bokstavpunkt og tilhørende tabeller for risikoklasse, areal, etasjer og brukerforutsetninger.",
    preacceptedPath: "Aktive anlegg må følge ytelsene og de standardene veiledningen uttrykkelig viser til.",
  }),
  sourceChunk({
    id: "11-12-sprinkler",
    section: "Veiledning til TEK17 § 11-12",
    paragraph: "første ledd bokstav a",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-12 Automatisk slokkeanlegg og sprinkler",
    referenceKeys: ["section11_12"],
    topics: ["sprinkler", "automatisk slokkeanlegg", "rkl 4", "heis", "åpen forbindelse", "overbygd gård"],
    phrases: ["risikoklasse 4 hvor det kreves heis", "automatisk sprinkleranlegg", "åpen forbindelse over flere plan"],
    shortAnswer: "Veiledningen angir situasjoner der automatisk slokkeanlegg er nødvendig eller inngår som preakseptert ytelse.",
    practicalMeaning: "Omfang, seksjonering og riktig standard må vurderes for hele byggverket eller den aktuelle delen.",
    vtekSearch: "Kontroller risikoklasse, heiskrav, åpne forbindelser, areal og eventuell overbygd gård.",
    preacceptedPath: "Sprinkleranlegget må prosjekteres og utføres etter standarden og tilleggsvilkårene DIBK viser til.",
  }),
  sourceChunk({
    id: "11-13-exits",
    section: "TEK17 § 11-13",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-13 Utgang fra branncelle",
    referenceKeys: ["section11_13"],
    topics: ["utgang", "branncelle", "sikkert sted", "to rømningsveier", "rømningsretning", "trapperom", "fluktvei"],
    phrases: ["utgang fra branncelle", "to uavhengige rømningsveier", "to alternative rømningsretninger"],
    shortAnswer: "En branncelle skal ha utgang til sikkert sted eller til rømningsløsninger med tilstrekkelig uavhengighet.",
    practicalMeaning: "Utgangsprinsipp, avstander, antall trapperom og dimensjonerende persontall må vurderes samlet.",
    vtekSearch: "Avklar branncellens bruk, risikoklasse, persontall og mulige utgangsprinsipper.",
    preacceptedPath: "Veiledningen gir tabeller for fluktveilengde, trapperom og dimensjonerende persontall.",
  }),
  sourceChunk({
    id: "11-13-travel-distance",
    section: "Veiledning til TEK17 § 11-13",
    paragraph: "tabell 1 og 2",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-13 Fluktveilengde og trapperom",
    referenceKeys: ["section11_13"],
    topics: ["fluktveilengde", "maksimal avstand", "tr 1", "tr 2", "tr 3", "trapperom", "7 meter"],
    phrases: ["avstand til nærmeste utgang", "maksimal lengde på fluktvei", "minst to trapperom"],
    shortAnswer: "Veiledningen begrenser avstanden til nærmeste utgang og angir trapperomstype etter risikoklasse og etasjeantall.",
    practicalMeaning: "Maksimal fluktvei er normalt 50 meter i RKL 1-2, 30 meter i RKL 3 og 5, og 25 meter i RKL 6.",
    assessmentNote: "Måling, innredning, blindkorridorer og øvrige vilkår må kontrolleres i hele bestemmelsen.",
    vtekSearch: "Bruk riktig risikoklasse i tabell 1 og etasjeantall i tabell 2.",
    preacceptedPath: "Tabellverdier og alle tilhørende begrensninger må følges.",
  }),
  sourceChunk({
    id: "11-14-route",
    section: "TEK17 § 11-14",
    paragraph: "første ledd",
    sourceType: "forskriftskrav",
    title: "§ 11-14 Rømningsvei",
    referenceKeys: ["section11_14"],
    topics: ["rømningsvei", "korridor", "trapperom", "sikkert sted", "fri bredde", "rømningsretning"],
    phrases: ["egen branncelle", "oversiktlig og lettfattelig", "tilstrekkelig bredde og høyde"],
    shortAnswer: "Rømningsvei skal føre oversiktlig til sikkert sted og være dimensjonert og brannmessig skilt for rask rømning.",
    practicalMeaning: "Rømningsveien er normalt egen branncelle og må beskyttes mot røyk, flammer, hindringer og innsnevringer.",
    vtekSearch: "Kontroller korridor, trapperom, dører, avstander, bredder og utgang til sikkert sted.",
    preacceptedPath: "Veiledningen gir konkrete avstands- og breddeytelser etter risikoklasse og persontall.",
  }),
  sourceChunk({
    id: "11-14-width-distance",
    section: "Veiledning til TEK17 § 11-14",
    paragraph: "første ledd, preaksepterte ytelser",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-14 Bredde og avstand i rømningsvei",
    referenceKeys: ["section11_14"],
    topics: ["rømningsbredde", "fri bredde", "15 meter", "30 meter", "1 cm per person", "0,86 meter", "1,16 meter"],
    phrases: ["hvor bred", "samlet fri bredde", "avstand fra dør", "en centimeter per person"],
    shortAnswer: "Veiledningen angir avstand fra branncelledør til trapp eller sikkert sted og minimum fri bredde etter risikoklasse og persontall.",
    practicalMeaning: "Avstanden er normalt 15 meter ved én eller sammenfallende retning og 30 meter ved flere utganger; bredden må også dekke persontallet.",
    assessmentNote: "Krav i kapittel 12 gjelder dersom de gir større bredde.",
    vtekSearch: "Kontroller antall retninger, risikoklasse, persontall, universell utforming og samtidig rømning.",
    preacceptedPath: "Alle avstands-, bredde- og kapasitetsvilkår må være oppfylt samtidig.",
    keyPoints: [
      "Samlet fri bredde i rømningsvei skal være minst 1 cm per person.",
      "I RKL 1, 2 og 4 skal fri bredde være minst 0,86 meter.",
      "I RKL 3, 5 og 6 skal fri bredde være minst 1,16 meter. Boliger i RKL 6 kan ha minst 0,86 meter.",
    ],
  }),
  sourceChunk({
    id: "11-15-animals",
    section: "TEK17 § 11-15",
    paragraph: "bestemmelsen og preaksepterte ytelser",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-15 Redning av husdyr",
    referenceKeys: ["section11_15"],
    topics: ["husdyr", "husdyrrom", "driftsbygning", "fjøs", "stall", "rømning dyr", "utgangsbredde"],
    phrases: ["redning av husdyr", "to utganger", "passasje av to dyr"],
    shortAnswer: "Byggverk for husdyrhold skal gi rask og sikker redning av dyrene.",
    practicalMeaning: "Husdyrrom skal normalt ha minst to utganger, begrenset avstand og bredder tilpasset dyretypen.",
    vtekSearch: "Kontroller dyretype, utgangsantall, bredde, avstand og fare for blokkering av ytterdør.",
    preacceptedPath: "Veiledningens ytelser angir minst to utganger, maksimalt 30 meter og minimumsbredder etter dyretype.",
  }),
  sourceChunk({
    id: "11-16-manual-firefighting",
    section: "TEK17 § 11-16",
    paragraph: "første til fjerde ledd",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-16 Manuell slokking",
    referenceKeys: ["section11_16"],
    topics: ["manuell slokking", "brannslange", "håndslokker", "brannslokkeapparat", "pulverapparat", "slokkeutstyr", "merking"],
    phrases: ["effektiv manuell slokking", "slokkeinnsats i startfasen", "rekker inn i alle rom"],
    shortAnswer: "Alle byggverk der brann kan oppstå skal ha egnet manuelt slokkeutstyr for innsats i startfasen.",
    practicalMeaning: "Type, kapasitet, plassering, dekning og merking av utstyret avhenger av risiko og bruk.",
    vtekSearch: "Kontroller risikoklasse, tilgang på vann, særskilt brannrisiko, dekningsområde og plassering.",
    preacceptedPath: "Veiledningen angir brannslange for visse risikoklasser og brannslange eller håndslokker for andre, med krav til full dekning.",
  }),
  sourceChunk({
    id: "11-17-access",
    section: "TEK17 § 11-17",
    paragraph: "første ledd",
    sourceType: "preakseptert-ytelse",
    title: "§ 11-17 Atkomst for rednings- og slokkemannskap",
    referenceKeys: ["section11_17"],
    topics: ["brannvesen", "atkomst", "oppstillingsplass", "høyderedskap", "angrepsvei", "kjørebredde", "23 meter", "50 meter slangeutlegg"],
    phrases: ["rednings- og slokkemannskap", "brannvesenets høyderedskap", "kjørbar atkomst", "oppstillingsplass"],
    shortAnswer: "Byggverket og utearealene skal gi brannvesenet brukbar tilgjengelighet for rednings- og slokkeinnsats.",
    practicalMeaning: "Atkomstvei, oppstillingsplass, angrepsvei, høyderedskap, slangeutlegg og lokale dimensjoneringskriterier må avklares.",
    assessmentNote: "Ansvarlig prosjekterende må innhente lokale kriterier fra brannvesenet.",
    vtekSearch: "Kontroller høyde, etasjeantall, avstand til inngang, lokale kjøretøykrav og tilgang til alle deler av bygget.",
    preacceptedPath: "Veiledningen gir ytelser for blant annet bygg inntil åtte etasjer, 23 meters høydegrense og maksimalt slangeutlegg.",
  }),
  sourceChunk({
    id: "11-17-internal-access",
    section: "Veiledning til TEK17 § 11-17",
    paragraph: "tilgjengelighet i byggverket",
    sourceType: "veiledning",
    title: "§ 11-17 Angrepsvei, samband og orientering",
    referenceKeys: ["section11_17"],
    topics: ["angrepsvei", "radiodekning", "nødnett", "universalnøkkel", "orienteringsplan", "brannheis", "stigerør"],
    phrases: ["innvendig radiodekning", "mer enn 50 rom", "brannvesenets angrepsvei"],
    shortAnswer: "Brannvesenet må kunne komme inn, orientere seg, kommunisere og nå innsatsområdene uten unødig risiko.",
    practicalMeaning: "Store eller komplekse bygg kan kreve tiltak for nøkler, samband, orientering, stigerør eller andre innsatsforhold.",
    vtekSearch: "Avklar byggstørrelse, romantall, dekning, angrepsvei og behov for tekniske hjelpemidler.",
    preacceptedPath: "Følg de konkrete ytelsene i § 11-17 og lokale kriterier fra brannvesenet.",
  }),
  sourceChunk({
    id: "sak10-measure-class",
    section: "SAK10 §§ 9-3 og 9-4",
    paragraph: "tiltaksklasse",
    sourceType: "forskriftskrav",
    title: "SAK10 Tiltaksklasse",
    referenceKeys: ["measure93", "measure94", "measureGuide"],
    topics: ["tiltaksklasse", "tkl", "sak10", "ansvar", "prosjektering", "kompleksitet", "vanskelighetsgrad", "konsekvens"],
    phrases: ["fastsettelse av tiltaksklasse", "oppdeling i tiltaksklasser", "konsekvenser av feil"],
    shortAnswer: "Tiltaksklasse fastsettes for oppgaven eller fagområdet ut fra kompleksitet, vanskelighetsgrad og konsekvenser av feil.",
    practicalMeaning: "Risikoklasse, brannklasse og analysebehov er vurderingsmomenter, men gir ikke automatisk en bestemt tiltaksklasse.",
    assessmentNote: "Ansvarlig søker foreslår tiltaksklasse, mens kommunen fastsetter den.",
    vtekSearch: "Avklar hvilken konkret oppgave eller hvilket ansvarsfag som vurderes.",
    preacceptedPath: "Bruk kriteriene og eksemplene i SAK10 kapittel 9; tiltaksklasse er ikke en VTEK-ytelse.",
  }),
];
